sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_install:
  - npm install -g yarn@1.3.2
install:
  - npm install
before_script:
  - npm prune
script:
  - npm test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
